algoritmo "Exercício repita ate que imprima 50 números pares"
// Função :
// Autor :
// Data : 20/12/2024
// Seção de Declarações 
var

   numero, quantidade : inteiro

inicio

      numero <- 2
      
      quantidade <- 1

      Repita
      
             Escreval ( numero )
             numero <- numero + 2
             quantidade <- quantidade + 1
      
      
      Ate quantidade > 50
      


fimalgoritmo
