algoritmo "Função Se com Ou"
// Função :
// Autor :
// Data : 16/12/2024
// Seção de Declarações 
var

   cor : caractere

inicio

      Escreval ("Digite uma cor: ")
      leia (cor)
      
      Se ( cor = "Azul" ) ou ( cor = "Amarelo") Entao
      
           Escreval ("A cor digitada é Azul ou Amarelo")
      
      Senao

           Escreval ("Cor inválida!")
      
      FimSe
      

fimalgoritmo
