algoritmo "Para-de-Faca de 1 ate 20"
// Função :
// Autor :
// Data : 20/12/2024
// Seção de Declarações 
var

   numero : inteiro

inicio

     //Para <variável contadora> de <valor inicial> Ate <valor final> Faca
     
     //<instruções a serem executadas repetidamente até a <variável contadora> atingir o valor final>
     
     //FimPara

     Para numero de 1 ate 20 Faca
     
          Escreval ("Número: ", numero)
          
     FimPara



fimalgoritmo
